baseURL = 'http://wickerwaka.github.io/'
languageCode = 'en-us'
theme = 'hello-friend'
title = "Martin's DevBlog"
copyright = "© 2023 Martin Donlon"

[params]
contentTypeName = "posts"
defaultTheme = "dark"
showMenuItems = 2
showReadingTime = false
# toc = true
# rssFullText = true

subtitle = ""
keywords = ""
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"
# leave empty to disable, enter display text to enable
# lastModDisplay = ""

[params.logo]
    logoText = "devblog.txt"
    logoHomeLink = "/"

[menu]
    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"


[module]
[[module.imports]]
  path = 'github.com/hugomods/images'